---
packit_instances: ["prod", "stg"]
specfile_path: wait-for-copr.spec
files_to_sync:
  - .packit.yaml
  - wait-for-copr.spec
upstream_package_name: wait-for-copr
downstream_package_name: wait-for-copr

actions:
  create-archive:
    - "python3 -m build --sdist --outdir ."
    - "sh -c 'echo wait_for_copr-$(hatch version).tar.gz'"
  get-current-version:
    - "hatch version"

srpm_build_deps:
  - python3-build
  - hatch
  - python3-hatch-vcs

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  - job: copr_build
    trigger: commit
    branch: main
    targets:
      - fedora-all
      - epel-9
    project: packit-dev
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: commit
    branch: stable
    targets:
      - fedora-stable
      - epel-9
    project: packit-stable
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: release
    targets:
      - fedora-stable
      - epel-9
    project: packit-releases
    list_on_homepage: True
    preserve_project: True
